-- PostgreSQL
-- Estrutura principal esperada para a tabela tratada de ocorrências.
-- Ajuste tipos e caminhos conforme o banco usado localmente.

CREATE TABLE IF NOT EXISTS tratado.ocorrencias (
    id TEXT,
    data_inversa DATE,
    dia_semana TEXT,
    horario TEXT,
    uf TEXT,
    br INTEGER,
    km NUMERIC,
    municipio TEXT,
    causa_acidente TEXT,
    tipo_acidente TEXT,
    classificacao_acidente TEXT,
    fase_dia TEXT,
    sentido_via TEXT,
    condicao_metereologica TEXT,
    tipo_pista TEXT,
    tracado_via TEXT,
    uso_solo TEXT,
    pessoas INTEGER,
    mortos INTEGER,
    feridos_leves INTEGER,
    feridos_graves INTEGER,
    ilesos INTEGER,
    ignorados INTEGER,
    total_feridos_origem INTEGER,
    veiculos INTEGER,
    latitude TEXT,
    longitude TEXT,
    regional TEXT,
    delegacia TEXT,
    uop TEXT,
    ano INTEGER,
    arquivo_origem TEXT,
    mes INTEGER,
    hora INTEGER,
    faixa_horario TEXT,
    final_de_semana TEXT,
    total_feridos INTEGER,
    total_vitimas INTEGER,
    teve_morte TEXT,
    acidente_grave TEXT,
    nivel_gravidade TEXT
);

CREATE TABLE IF NOT EXISTS tratado.pessoas (
    id TEXT,
    pesid TEXT,
    data_inversa DATE,
    dia_semana TEXT,
    horario TEXT,
    uf TEXT,
    br INTEGER,
    km NUMERIC,
    municipio TEXT,
    causa_acidente TEXT,
    tipo_acidente TEXT,
    classificacao_acidente TEXT,
    fase_dia TEXT,
    tipo_envolvido TEXT,
    estado_fisico TEXT,
    idade INTEGER,
    sexo TEXT,
    ilesos INTEGER,
    feridos_leves INTEGER,
    feridos_graves INTEGER,
    mortos INTEGER,
    ano INTEGER,
    arquivo_origem TEXT
);
